// config.js - Central configuration for pricing, games, and backend credentials

const APP_CONFIG = {
    // Supabase Backend Credentials
    supabaseUrl: 'https://mwxndccwzkcsyvslucjg.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eG5kY2N3emtjc3l2c2x1Y2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0MTY1MjksImV4cCI6MjEwNTk5MjUyOX0.61NvDZ6cPnxLqoxJ4tr-H729a99h_XOAZDXo3zfx25g',

    // WhatsApp Contact Number
    whatsappNumber: '601165676869',

    // Jailbreak base prices by console model
    jailbreakPrices: {
        'OLED': 300,
        'V1_V2': 190,
        'LITE': 230
    },

    // System Setup flat base price (RM)
    systemSetupPrice: 50,

    // SD Card retail prices if they buy a card from you (RM)
    sdCardRetailPrices: {
        128: 110,
        256: 200,
        512: 400,
    },

    // Additional system mode pricing (+RM30 each)
    addonPrices: {
        android: 30,
        linux: 30
    },

    // ===== PROGRESS TRACKER STAGES =====
    progressStages: [
        'Order Received',
        'Confirmed',
        'In Progress',
        'Ready for Pickup',
        'Completed'
    ],

    // Customer-facing descriptions for each stage
    progressDescriptions: {
        'Order Received':   "We've received your order. We'll confirm the details on WhatsApp and arrange a drop-off time.",
        'Confirmed':        "Details confirmed. Please drop off your console so we can begin work.",
        'In Progress':      "Your console is being prepared. See details below.",
        'Ready for Pickup': "Your console is ready. Come collect it anytime — payment on pickup.",
        'Completed':        "Thanks for your business. Enjoy your games."
    },

    // Sub-stages per service type
    subStagesByService: {
        'jailbreak':    ['Modchip Installation', 'System Setup', 'Game Installation'],
        'system_setup': ['System Setup', 'Game Installation'],
        'games_only':   ['Game Installation']
    },

    // Customer-facing description per sub-stage
    subStageDescriptions: {
        'Modchip Installation': "Installing the modchip hardware into your console.",
        'System Setup':         "Configuring bootloader, firmware, and system software.",
        'Game Installation':    "Copying your selected games onto the SD card."
    },

    // ===== OPTIONAL: Estimated time per substage (toggle via showEstimatedTime) =====
    showEstimatedTime: true,
    subStageEstimatedTimes: {
        'Modchip Installation': "~1 day",
        'System Setup':         "~2 hours",
        'Game Installation':    "~1–2 hours"
    }
};

// Your game catalog library - automatically updated by your PowerShell script!
const games = [
      { name: "1-2-Switch", size: 1.39 },
      { name: "A Little to the Left", size: 1.91 },
      { name: "Absolum", size: 2.44 },
      { name: "Ace Combat 7 Skies Unknown (US)", size: 13.1 },
      { name: "AEW Fight Forever", size: 14.36 },
      { name: "Alien Isolation", size: 14.48 },
      { name: "Animal Crossing New Horizons", size: 10.84 },
      { name: "AO Tennis 2", size: 8.14 },
      { name: "Assassins Creed The Ezio Collection", size: 28.73 },
      { name: "Assassins Creed The Rebel Collection", size: 13.6 },
      { name: "Attack on Titan 2 Final Battle", size: 18.54 },
      { name: "Avatar The Last Airbender - Quest for Balance", size: 3.82 },
      { name: "Batman Arkham Trilogy", size: 44.11 },
      { name: "Bayonetta 1+2", size: 18.16 },
      { name: "Bayonetta 3", size: 15.91 },
      { name: "Beyblade 1-2", size: 4.1 },
      { name: "Beyond Good and Evil 20th Anniversary Edition", size: 7.98 },
      { name: "Big Brain Academy Brain vs Brain", size: 0.51 },
      { name: "Bioshock the Collection", size: 35.34 },
      { name: "Blasphemous II", size: 1.77 },
      { name: "Bravely Default II", size: 12.4 },
      { name: "Bright Memory Infinite", size: 2.15 },
      { name: "Burnout Paradise Remastered", size: 2.48 },
      { name: "Capcom Fighting Collection 1-2", size: 6.26 },
      { name: "Captain Blood", size: 3.37 },
      { name: "Captain Toad Treasure Tracker", size: 1.89 },
      { name: "Cars 3", size: 3.27 },
      { name: "Celeste", size: 0.91 },
      { name: "Chef Life a Restaurant Simulator", size: 3.46 },
      { name: "Circuit Superstars", size: 1.34 },
      { name: "Cities Skylines", size: 0.97 },
      { name: "Clubhouse Games 51 Worldwide Classics", size: 2.74 },
      { name: "CoComelon - Play with JJ", size: 1.03 },
      { name: "Cocoon", size: 1.3 },
      { name: "Contra Operation Galuga", size: 7.03 },
      { name: "Cookie Cutter Overkill Edition", size: 0.96 },
      { name: "Crash Bandicoot 4 Its About Time", size: 9.27 },
      { name: "Crash Team Racing Nitro-Fueled", size: 6.78 },
      { name: "Croc Legend of the Gobbos", size: 5.92 },
      { name: "Crysis 1-2-3 Remastered", size: 23.88 },
      { name: "Cult of the Lamb", size: 1.83 },
      { name: "Cuphead", size: 4.16 },
      { name: "Dark Souls Remastered", size: 4.01 },
      { name: "Darksiders 3", size: 7.46 },
      { name: "Dave the Diver", size: 3.4 },
      { name: "Dead Cells", size: 2.39 },
      { name: "Deer and Boy", size: 3.34 },
      { name: "Deltarune Chap. 1-4", size: 0.62 },
      { name: "Demon Slayer 2", size: 16.45 },
      { name: "Demon Slayer The Hinokami Chronicles Kimetsu no Yaiba", size: 11.07 },
      { name: "Devil May Cry Trilogy", size: 13.15 },
      { name: "Diablo 3", size: 22.25 },
      { name: "Digimon Story Cyber Sleuth Complete Edition", size: 3.84 },
      { name: "Digimon Story Time Stranger", size: 9.19 },
      { name: "Digimon Survive", size: 3.73 },
      { name: "Digimon World Next Order (EU)", size: 4.55 },
      { name: "Disaster Report 4 Summer Memories", size: 14.69 },
      { name: "Disney Dreamlight Valley", size: 15.8 },
      { name: "Disney Epic Mickey Rebrushed", size: 11.66 },
      { name: "Disney Illusion Island", size: 5.83 },
      { name: "Disney Speedstorm", size: 3.26 },
      { name: "Disney Tsum Tsum Festival", size: 2.1 },
      { name: "Donkey Kong Country Returns HD", size: 8.31 },
      { name: "Donkey Kong Country Tropical Freeze", size: 6.69 },
      { name: "DOOM Eternal", size: 25.57 },
      { name: "Dr Kawashimas Brain Training", size: 0.37 },
      { name: "Dragon Ball series for Nintendo Switch", size: 24.56 },
      { name: "Dragon Ball Sparking Zero", size: 6.06 },
      { name: "Dragon Ball Z Kakarot + A New Power Awakens Set", size: 21.89 },
      { name: "Dragon Quest I and II HD-2D Remake", size: 6.83 },
      { name: "Dragon Quest III HD 2D Remake", size: 7.68 },
      { name: "Dragon Quest XI S Echoes of an Elusive Age Definitive Edition", size: 11 },
      { name: "Dredge", size: 0.98 },
      { name: "Drop Duchy Complete edition", size: 1.79 },
      { name: "Dtopia", size: 1.11 },
      { name: "EA Sports FC 24", size: 51.3 },
      { name: "EA SPORTS FC 25", size: 32.05 },
      { name: "EA Sports FC 26", size: 30.91 },
      { name: "ENDER LILIES Quietus of the Knights", size: 1.76 },
      { name: "Ender Magnolia Bloom in the Mist", size: 3.63 },
      { name: "Fairy Tail 2 (US)", size: 3.98 },
      { name: "Fairy Tail", size: 3.51 },
      { name: "Fantasy Life i The Girl Who Steals Time", size: 5.67 },
      { name: "Farm simulators for Nintendo Switch", size: 0.9 },
      { name: "Fever Sport collection 1-4", size: 1.08 },
      { name: "FIFA 2023 Legacy edition", size: 12.49 },
      { name: "Final Fantasy VII Reunion Crisis Core", size: 14.63 },
      { name: "Fire Emblem Engage", size: 13.46 },
      { name: "Fire Emblem Three Houses", size: 12.59 },
      { name: "Fishing games for Nintendo Switch", size: 4.82 },
      { name: "FIST Forged in Shadow Torch", size: 6.29 },
      { name: "Fitness Boxing 3", size: 2.79 },
      { name: "Football Manager 26 Touch", size: 3.67 },
      { name: "Gas Station Simulator", size: 3.62 },
      { name: "Gear Club Unlimited 1-2", size: 5.06 },
      { name: "Go Vacation", size: 3.66 },
      { name: "Grand Theft Auto V (homebrew port) for Nintendo Switch", size: 48.98 },
      { name: "Grid Autosport", size: 7.68 },
      { name: "GTA The Trilogy", size: 42.2 },
      { name: "Hades II", size: 6.45 },
      { name: "Hades", size: 5.76 },
      { name: "Harvest Moon - The Winds of Anthos", size: 2.21 },
      { name: "Harvest Moon One World", size: 1.32 },
      { name: "Harvest Moon the Lost Valley and Skytree Village", size: 0.36 },
      { name: "Hello Kitty Island Adventure", size: 2.84 },
      { name: "High on Life", size: 9.59 },
      { name: "Hitman Absolution", size: 10.61 },
      { name: "Hogwarts Legacy", size: 14.87 },
      { name: "Hollow Knight Silksong", size: 1.9 },
      { name: "Hollow Knight", size: 0.91 },
      { name: "Hot Wheels Lets Race Ultimate Speed", size: 2.27 },
      { name: "Hot Wheels Unleashed 2 Turbocharged", size: 6.9 },
      { name: "Hot Wheels Unleashed", size: 7.13 },
      { name: "House Flipper", size: 3 },
      { name: "Human Fall Flat", size: 1.7 },
      { name: "Hyrule Warriors Age of Calamity", size: 10.1 },
      { name: "Inazuma Eleven Victory Road", size: 26.5 },
      { name: "Inkonbini One Store Many Stories", size: 1.26 },
      { name: "It Takes Two", size: 12.13 },
      { name: "Jujutsu Kaisen Cursed Clash", size: 7.81 },
      { name: "Jumanji the Curse Returns", size: 0.67 },
      { name: "Jump Force Deluxe Edition (EU)", size: 10.14 },
      { name: "Just Dance 2025 plus Offline Mod", size: 19.37 },
      { name: "Just Dance Legacy MOD", size: 147.44 },
      { name: "Kamen Rider 1-2", size: 4.87 },
      { name: "Kiborg", size: 3.01 },
      { name: "Kingdom Come Deliverance - Royal Edition", size: 14.43 },
      { name: "Kirby and the Forgotten Land", size: 5.75 },
      { name: "Kirby Star Allies", size: 2.4 },
      { name: "Kirbys Return to Dream Land Deluxe", size: 5 },
      { name: "LEGO City Undercover", size: 6.58 },
      { name: "LEGO DC Super-Villains", size: 9.65 },
      { name: "LEGO Horizon Adventures", size: 7.22 },
      { name: "LEGO Party", size: 5.89 },
      { name: "LEGO Star Wars The Skywalker Saga", size: 15.99 },
      { name: "Little Kitty Big City", size: 0.66 },
      { name: "Little Nightmares 2", size: 2.66 },
      { name: "Little Nightmares III", size: 9.46 },
      { name: "Lost in Play", size: 1.16 },
      { name: "Lost in Random the Eternal Die", size: 1.89 },
      { name: "Luigis Mansion 2 HD", size: 2.99 },
      { name: "Luigis Mansion 3", size: 6.79 },
      { name: "Mandragora Whispers of the Witch Tree (EU)", size: 6.38 },
      { name: "Mandragora Whispers of the Witch Tree", size: 5.68 },
      { name: "Mario and Luigi Brothership", size: 9.85 },
      { name: "Mario and Sonic at the Olympic Games Tokyo 2020", size: 4.47 },
      { name: "Mario Golf Super Rush", size: 4.17 },
      { name: "Mario Kart 8 Deluxe", size: 11.17 },
      { name: "Mario Party Superstars", size: 2.85 },
      { name: "Mario Strikers Battle League", size: 2.77 },
      { name: "Mario Tennis Aces", size: 2.42 },
      { name: "Mario vs. Donkey Kong", size: 1.3 },
      { name: "Marvel Cosmic Invasion", size: 0.58 },
      { name: "Marvel Maximum Collection", size: 1.38 },
      { name: "Marvel Ultimate Alliance 3 The Black Order + DLC", size: 14.3 },
      { name: "Marvel vs Capcom Fighting Collection Arcade Classics", size: 3.16 },
      { name: "MathLand", size: 0.21 },
      { name: "Mega Man Star Force Legacy Collection {NSP]", size: 7.62 },
      { name: "Megaman Battle Network Legacy Collection Vol 1-2", size: 2.76 },
      { name: "Metal Slug Attack Reloaded", size: 3.29 },
      { name: "Metro Redux", size: 9.98 },
      { name: "Metroid Dread", size: 3.23 },
      { name: "Metroid Prime 4 Beyond", size: 21.84 },
      { name: "Metroid Prime Remastered", size: 6.76 },
      { name: "MGS Master Collection Vol 2", size: 29.51 },
      { name: "MGS Master Collection", size: 46.17 },
      { name: "Minecraft Dungeons", size: 3.9 },
      { name: "Minecraft Legends", size: 7.34 },
      { name: "Minecraft", size: 2.55 },
      { name: "Mobile Suit Gundam Seed Battle Destiny", size: 5.46 },
      { name: "MOBILE-SUIT-GUNDAM-SEED-BATTLE-DESTINY-REMASTERED-Switch-BASE-GAME.XCI", size: 5.82 },
      { name: "Monopoly 2024", size: 1.37 },
      { name: "Monster Hunter Rise", size: 19.79 },
      { name: "Monster Hunter Stories", size: 7.7 },
      { name: "Monument Valley 1-2", size: 0.5 },
      { name: "Moonlight Peaks", size: 1.96 },
      { name: "Morbid the Lords of Ire", size: 3.08 },
      { name: "Mortal Kombat 1", size: 40.03 },
      { name: "Mortal Kombat 11", size: 28.25 },
      { name: "MotoGP 23", size: 11.13 },
      { name: "MotoGP 25", size: 8.52 },
      { name: "MotoGP24", size: 10.75 },
      { name: "Moving Out 2", size: 1.69 },
      { name: "My Hero Ones Justice", size: 14.47 },
      { name: "My Sims Cozy Bundle", size: 3.18 },
      { name: "NARUTO", size: 12.25 },
      { name: "Naruto Shippuden Ultimate Ninja Storm Trilogy", size: 17.63 },
      { name: "Naruto x Boruto Ultimate Ninja Storm Connections (EU)", size: 17.4 },
      { name: "NBA 2K25", size: 58.63 },
      { name: "Need for Speed Hot Pursuit Remastered", size: 6.21 },
      { name: "New Super Luckys Tale", size: 4.97 },
      { name: "New Super Mario Bros U Deluxe", size: 1.39 },
      { name: "Nickelodeon All-Star Brawl 2", size: 6.31 },
      { name: "Nickelodeon All-Star Brawl", size: 4.68 },
      { name: "Nickelodeon Kart Racers 1-2-3", size: 8.98 },
      { name: "NieR Automata The End of YoRHa Edition", size: 10.91 },
      { name: "Nikoderiko the Magical World", size: 6.47 },
      { name: "Ninja Gaiden Ragebound", size: 1.04 },
      { name: "Nintendo Switch Sports", size: 3.24 },
      { name: "Octopath Traveler 2", size: 6.08 },
      { name: "Octopath Traveler", size: 2.59 },
      { name: "Old School Rally", size: 0.61 },
      { name: "Once Upon a Katamari", size: 2.49 },
      { name: "One Piece Odyssey Deluxe Edition", size: 9.9 },
      { name: "One Piece", size: 29.56 },
      { name: "Onimusha 2 Samurais Destiny", size: 13.05 },
      { name: "Ori and the Will of the Wisps", size: 3.32 },
      { name: "Out of Sight", size: 4.11 },
      { name: "Outlast 1+2", size: 8.86 },
      { name: "Overcooked 1+2", size: 4.67 },
      { name: "Paper Mario The Thousand-Year Door", size: 5.08 },
      { name: "Pascals Wager Definitive Edition", size: 5.51 },
      { name: "Persona 5 Royal", size: 11.73 },
      { name: "Pico Park 1-2", size: 0.16 },
      { name: "Pikmin 4", size: 10.48 },
      { name: "Pizza Tower", size: 0.75 },
      { name: "Plants vs Zombies Battle for Neighborville", size: 4.87 },
      { name: "Plants vs. Zombies Replanted for Nintendo Switch", size: 2.34 },
      { name: "Pokemon Brilliant Diamond and Shining Pearl", size: 3.86 },
      { name: "Pokemon Fire Red and Leaf Green", size: 0.07 },
      { name: "Pokemon Legends Arceus", size: 2.22 },
      { name: "Pokemon Legends Z-A", size: 5.32 },
      { name: "Pokemon Lets Go Eevee + Pikachu + Quest + Torunament DX", size: 12.67 },
      { name: "Pokemon Scarlet and Violet", size: 11.15 },
      { name: "Pokemon Sword and Shield", size: 5.66 },
      { name: "Portal Companion Collection", size: 10 },
      { name: "Potion Craft", size: 0.54 },
      { name: "Power Rangers Battle for the Grid", size: 1.85 },
      { name: "Prince of Persia the Lost Crown", size: 5.24 },
      { name: "Princess Peach Showtime!", size: 4.65 },
      { name: "Rabbids Party of Legends", size: 3 },
      { name: "Rayman", size: 2.99 },
      { name: "Red Dead Redemption", size: 10.19 },
      { name: "Red Faction Guerrilla Re-Mars-tered", size: 13.82 },
      { name: "Red Wings 1-3", size: 2.12 },
      { name: "Remnant From the Ashes", size: 7.16 },
      { name: "Resident Evil 4", size: 8.22 },
      { name: "Resident Evil 5-6", size: 12.92 },
      { name: "Resident Evil Revelations 1-2", size: 27.92 },
      { name: "Reynatis (US)", size: 8.2 },
      { name: "Rhythm Heaven Groove", size: 2.49 },
      { name: "Ridge Racer 8 (DEV PROTOTYPE)", size: 2.76 },
      { name: "Rise Race the Future", size: 1.98 },
      { name: "Rune Factory Guardians of Azuma", size: 5.99 },
      { name: "Rush Rally", size: 0.45 },
      { name: "Saints Row", size: 12.16 },
      { name: "Scott Pilgrim EX", size: 0.94 },
      { name: "SD Gundam 1-2", size: 26.14 },
      { name: "Sea of Stars", size: 3.22 },
      { name: "Serious Sam Collection", size: 4.28 },
      { name: "Shin chan 1-2", size: 3.55 },
      { name: "Shin Megami Tensei 5 Vengeance", size: 14.1 },
      { name: "Shin Megami Tensei V", size: 16.42 },
      { name: "Shinobi Art of Vengeance", size: 6.8 },
      { name: "Sid Meiers Civilization VII", size: 4.07 },
      { name: "Sifu", size: 5.82 },
      { name: "Sniper Elite 2-3", size: 13.49 },
      { name: "Sniper Elite 4", size: 9.01 },
      { name: "Snipperclips Cut it out Together", size: 0.56 },
      { name: "Snowrunner", size: 14.59 },
      { name: "Sonic Frontiers", size: 11.95 },
      { name: "Sonic Mania", size: 0.37 },
      { name: "Sonic Racing Cross Worlds", size: 8.86 },
      { name: "Sonic Superstars", size: 6.22 },
      { name: "Sonic x Shadow Generation", size: 10.25 },
      { name: "Splatoon 3", size: 12.67 },
      { name: "Split", size: 0.61 },
      { name: "Sponge Bob Square Pants the Cosmic Shake", size: 7.01 },
      { name: "SpongeBob Krusty Cook Off", size: 0.49 },
      { name: "SpongeBob SquarePants Battle for Bikini Bottom Rehydrated", size: 9.38 },
      { name: "SpongeBob SquarePants the Patrick Star Game", size: 0.68 },
      { name: "Stardew Valley", size: 1.95 },
      { name: "Stray", size: 4.45 },
      { name: "Street Fighterr 30th Anniversary Collection", size: 5.11 },
      { name: "Super Bomberman R", size: 2.55 },
      { name: "Super Bomberman R2", size: 2.66 },
      { name: "Super Mario 3D All-Stars", size: 4.91 },
      { name: "Super Mario 3D World Bowsers Fury", size: 2.13 },
      { name: "Super Mario Bros Wonder", size: 3.56 },
      { name: "Super Mario Galaxy 1-2", size: 6.51 },
      { name: "Super Mario Maker 2", size: 3.09 },
      { name: "Super Mario Odyssey", size: 5.78 },
      { name: "Super Mario Party Jamboree", size: 5.35 },
      { name: "Super Mario RPG", size: 5.54 },
      { name: "Super Monkey Ball Banana Rumble", size: 3.58 },
      { name: "Super Robot Wars", size: 34.61 },
      { name: "Super Smash Bros Ultimate", size: 14.17 },
      { name: "Tamagotchi Plaza", size: 0.75 },
      { name: "Teenage Mutant Ninja Turtles Shredders Revenge", size: 1.05 },
      { name: "The Bridge Curse 1-2", size: 6.57 },
      { name: "The House of the Dead 2 Remake", size: 2.83 },
      { name: "The House of The Dead Remake", size: 1.59 },
      { name: "The Hundred Line Last Defense Academy", size: 13.4 },
      { name: "The King of Fighters 13 Global Match", size: 2.55 },
      { name: "The Last Faith", size: 2.89 },
      { name: "The Legend of Heroes Sen no Kiseki I KAI (ENG Mod)", size: 3.15 },
      { name: "The Legend of Heroes Trails from Zero", size: 3.48 },
      { name: "The Legend of Heroes Trails Through Daybreak", size: 6.02 },
      { name: "The Legend of Heroes Trails to Azure", size: 4.92 },
      { name: "The Legend of Zelda Breath of the Wild", size: 15.71 },
      { name: "The Legend of Zelda Echoes of Wisdom", size: 4.44 },
      { name: "The Legend of Zelda Links Awakening", size: 1.93 },
      { name: "The Legend of Zelda Tears of the Kingdom", size: 16.3 },
      { name: "The Plucky Squire", size: 10.33 },
      { name: "The Walking Dead for Nintendo Switch", size: 31.34 },
      { name: "The Wanderer Frankensteins Creature", size: 1.04 },
      { name: "The Witcher 3 Wild Hunt - Complete Edition (EU)", size: 31.92 },
      { name: "Tiny Bookshop", size: 0.41 },
      { name: "Tomb Raider Definitive edition", size: 22.69 },
      { name: "Tomodachi Life Living the Dream", size: 6.35 },
      { name: "Tony Hawks Pro Skater 3+4", size: 18.19 },
      { name: "Tony Hawks Pro Skater 1+2", size: 8.89 },
      { name: "Tridents Tale", size: 3.21 },
      { name: "Twin Stick Arcade Shooters pack for Nintendo Switch", size: 1.14 },
      { name: "Unicorn Overlord", size: 5.75 },
      { name: "Unpacking", size: 0.32 },
      { name: "Unravel Two", size: 1.81 },
      { name: "Untitled Goose Game", size: 0.33 },
      { name: "Upin and Ipin Universe", size: 4.71 },
      { name: "Viewfinder", size: 2.61 },
      { name: "Vigil The Longest Night", size: 3.95 },
      { name: "WarioWare Get It Together", size: 1.52 },
      { name: "WarioWare Move It", size: 1.31 },
      { name: "Wolfenstein II The New Colossus", size: 22.08 },
      { name: "World of Goo 2", size: 0.64 },
      { name: "World War Z", size: 7.12 },
      { name: "WRC 8-9-10", size: 11.71 },
      { name: "Wreckfest", size: 7.36 },
      { name: "WWE 1-2", size: 27.2 },
      { name: "Xenoblade Chronicles 2 + Torna - The Golden Country + DLC", size: 14.92 },
      { name: "Xenoblade Chronicles 3", size: 18.75 },
      { name: "Xenoblade Chronicles Definitive Edition", size: 10.98 },
      { name: "Xenoblade Chronicles X Definitive Edition", size: 13.63 },
      { name: "Yakuza Kiwami Switch edition", size: 14.28 },
      { name: "Yoshis Crafted World", size: 5.6 },
      { name: "Ys Memories of Celceta (JAP+ENG MOD)", size: 5.96 },
      { name: "YS X Nordics (JAP)", size: 4.9 },
      { name: "Zombie Army Trilogy", size: 3.98 }
    ];